// Generated by: supabase gen types typescript --project-id <your-project-id> > src/lib/database.types.ts
// Re-run this command whenever the database schema changes.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      albums: {
        Row: {
          id: string;
          title: string;
          description: string;
          event_date: string;
          year: number;
          cover_url: string;
          cover_public_id: string;
          is_private: boolean;
          display_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          description?: string;
          event_date: string;
          cover_url?: string;
          cover_public_id?: string;
          is_private?: boolean;
          display_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          description?: string;
          event_date?: string;
          cover_url?: string;
          cover_public_id?: string;
          is_private?: boolean;
          display_order?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
      photos: {
        Row: {
          id: string;
          album_id: string;
          title: string;
          note: string;
          url: string;
          public_id: string;
          width: number | null;
          height: number | null;
          display_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          album_id: string;
          title?: string;
          note?: string;
          url: string;
          public_id: string;
          width?: number | null;
          height?: number | null;
          display_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          album_id?: string;
          title?: string;
          note?: string;
          url?: string;
          public_id?: string;
          width?: number | null;
          height?: number | null;
          display_order?: number;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'photos_album_id_fkey';
            columns: ['album_id'];
            referencedRelation: 'albums';
            referencedColumns: ['id'];
          }
        ];
      };
    };
    Views: Record<string, never>;
    Functions: {
      reorder_albums: {
        Args: { updates: Json };
        Returns: undefined;
      };
      reorder_photos: {
        Args: { updates: Json };
        Returns: undefined;
      };
      is_owner: {
        Args: Record<PropertyKey, never>;
        Returns: boolean;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
